### ISSUE TITLE
Error each time lyo is ran over a new package.

### ISSUE THREAD

**Issue by GMartigny** [bokub/lyo-service#1]
When I try to run lyo-service over a package that's not already compiled (ex: `left-pad`), I always get an error:
`Error: ENOENT: no such file or directory, rename '/home/nowuser/src/tmp/node_modules/npm-module-stats/node_modules/npm/node_modules/dezalgo' -> '/home/nowuser/src/tmp/node_modules/npm-module-stats/node_modules/npm/node_modules/.dezalgo.DELETE'`

Looks like Z͘à͉̟l̞̪g̪̪̝̬͚̼͠o҉ is released, run for your life !

**Comment by bokub** [comment]
The problem was already reported in the [dezalgo issue #7](https://github.com/npm/dezalgo/issues/7)

I redeployed the server so `node_modules` was deleted, and the problem now seems to be solved: https://lyo.now.sh/left-pad

Was left-pad the only package having issues?

**Comment by GMartigny** [comment]
I tried a few packages and all seems to work fine now. Thanks !
